#### DevSpace Helm Chart ####
# This is a highly configurable Helm chart. For information on how to configure this file,
# take a look at the documentation: https://devspace.cloud/docs/cli/deployment/components/configuration/overview-specification

# A list of containers that should run the pods of this component
containers: []
initContainers: []

service:
  type: ClusterIP
  labels: {}
  annotations: {}
  ports: []
  externalIPs: []

labels: {}
annotations: {}

ingress:
  disabled: false
  labels: {}
  annotations: {}
  certmanager: true
  rules: []

# Define persistent volumes here
# Then mount them in containers above
volumes: []

# Defines image pull secrets
# DevSpace CLI will append all pull secrets which are automatically created
# More infos on: https://devspace.cloud/docs/cli/image-building/workflow-basics#8-create-image-pull-secret
pullSecrets: []

virtualService:
  disabled: true

#   disabled: false
#   name: "my-app-vs"
#   gateways:
#     - "my-gateway"
#   labels:
#     environment: "prod"
#   annotations:
#     owner: "team-x"
#   rules:
#     - host: "app.example.com"
#       serviceName: "my-app"
#       servicePort: 8080
#       match:
#         - prefix: "/"
#       retries:
#         attempts: 3
#         perTryTimeout: 2s
#         retryOn: "5xx"
#       timeout: 10s
#       corsPolicy:
#         allowOrigins:
#           - exact: "https://example.com"
#         allowMethods:
#           - GET
#           - POST
#         allowCredentials: true
#     - host: "api.example.com"
#       serviceName: "my-api"
#       servicePort: 8081
#       match:
#         - prefix: "/api"
